name: test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run test:ci


    - uses: actions/checkout@v2
    - name: Use Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - run: deno --version
    - run: deno run --unstable --allow-net --import-map=import_map.json test/memstore.test.js
